import { NavItem } from '../models/sidebar.model';

export const sidebarMenu: NavItem[] = [
    // { name: 'Additional B2B Billing', path: '/custom-final-billing', key: 'cargox_custom_final_billing', icon: 'lucideReceipt' },
    // { name: 'AWB Order Report', path: '/awb-order-report', key: 'awb_order_report', icon: 'lucideFileText' },
    // { name: 'B2B Rates Upload', path: '/upload-heavy-bulky', key: 'heavy_bulky_uploads', icon: 'lucideUpload' },
    // { name: 'Bulk Upload Additional Billing', path: '/sr-awb-uploader-cargo-int', key: 'srawb_uploader_cargox', icon: 'lucideUpload' },
    // { name: 'Cancel AWB', path: '/awb-cancel', key: 'awb_cancel', icon: 'lucideBan' },
    // { name: 'Cancel Shipments', path: '/cancel-shipments', key: 'cancel_shipment', icon: 'lucideBan' },
    // { name: 'CargoX Custom Order Pricing', path: '/custom-order-pricing', key: 'cargox_custom_order_pricing', icon: 'lucideCalculator' },
    // { name: 'Close RTO Dispute', path: '/close-rto-dispute', key: 'close_rto_dispute', icon: 'lucideCircleX' },
    // { name: 'Cost Uploader', path: '/cost-uploader', key: 'cost_uploader', icon: 'lucideUpload' },
    // { name: 'Courier Management', path: '/courier-management', key: 'courier_management', icon: 'lucideBuilding' },
    { name: 'Courier Rate Card', path: '/courier-rate-card', key: 'cost_center', icon: 'lucideCreditCard' },
    { name: 'DDP Charges', path: '/ddp-charges', key: 'ddp_charge', icon: 'lucideDollarSign' },
    // { name: 'Deactivate Rates & Ranking', path: '/deactivate-rates-ranking-int', key: 'deactivate_rates_ranking', icon: 'lucideToggleLeft' },
    // { name: 'Download Rates & Ranking', path: '/download-rates-ranking', key: 'download_rates_ranking', icon: 'lucideDownload' },
    // { name: 'HSN Activation/Deactivation', path: '/hsn-activation-deactivation', key: 'hsn_data', icon: 'lucideToggleRight' },
    // { name: 'International Bulk KYC', path: '/international-bulk-kyc', key: 'international_bulk_kyc', icon: 'lucideList' },
    // { name: 'International Expedite Escalation', path: '/international-expedite-escalation', key: 'international_expedite_escalation', icon: 'lucideZap' },
    // { name: 'International HSN CTSH Mapping Upload', path: '/hsn-ctsh', key: 'sr_international_hsn_ctsh_upload', icon: 'lucideFileSpreadsheet' },
    // { name: 'International KAM Mapping', path: '/srx-kam-change', key: 'international_kam', icon: 'lucideUsers' },
    // { name: 'International KYC', path: '/international-kyc-admin', key: 'international_kyc', icon: 'lucideList' },
    // { name: 'International Manifest Download', path: '/international-manifest-download', key: 'international_manifest_download', icon: 'lucideDownload' },
    // { name: 'International Weight Dispute Report', path: '/international-weight-dispute-report', key: 'international_weight_dispute_report', icon: 'lucideScale' },
    // { name: 'International WD Image Upload', path: '/wd-image-international', key: 'international_wd_image_upload', icon: 'lucideUpload' },
    // { name: 'LM Uploader', path: '/lm-uploader-cargo-int', key: 'lm_uploader_cargox', icon: 'lucideUpload' },
    // { name: 'Last Mile Volume Upload', path: '/lastmile-volume-upload', key: 'lastmile_volume_upload', icon: 'lucideBarChart3' },
    // { name: 'Manifest Escalation', path: '/manifest-escalation', key: 'mainfest_escalation', icon: 'lucideTruck' },
    // { name: 'MIS International Upload', path: '/wd-mis-cbt', key: 'sr_international_mis', icon: 'lucideFileSpreadsheet' },
    // { name: 'MIS Upload', path: '/wd-mis', key: 'wd_mis_upload', icon: 'lucideFileSpreadsheet' },
    { name: 'Master AWB Upload', path: '/master-awb-upload', key: 'master_awb_upload', icon: 'lucideUpload' },
    // { name: 'PID Order Report', path: '/pid-order-report', key: 'pid_order_report', icon: 'lucideFileText' },
    // { name: 'Pickup Escalation', path: '/pickup-escalation', key: 'pickup_ids', icon: 'lucideTruck' },
    // { name: 'Pickup Generate Logs', path: '/pickup-generate-logs', key: 'pickup_generate_logs', icon: 'lucideFileText' },
    // { name: 'Quote Creation', path: '/quote-creation', key: 'quote_creation', icon: 'lucideQuote' },
    // { name: 'Refund Vas Charges', path: '/refund-legal-penalties-charges', key: 'refund_legal_penalty_charges', icon: 'lucideReceipt' },
    // { name: 'Seller Info', path: '/seller-listing', key: 'admin_seller', icon: 'lucideUser' },
    // { name: 'Shipment Details', path: '/shipment-listing', key: 'admin_shipment', icon: 'lucideTruck' },
    // { name: 'Upload International Shipping Bill', path: '/international-shipping-bill-upload', key: 'upload_international_shipping_bill', icon: 'lucideUpload' },
    // { name: 'Upload Rates & Ranking', path: '/upload-rates-ranking', key: 'upload_rates_ranking', icon: 'lucideUpload' },
    // { name: 'VCN Builder', path: '/vcn-builder', key: 'vcnBuilder', icon: 'lucideWrench' },
    // { name: 'WD Resolved Sheet', path: '/wd-resolved-sheet', key: 'wd_resolve_sheet', icon: 'lucideFileCheck' },
    // { name: 'Weight Escalation', path: '/wd-weight-escalation', key: 'wd_escalation', icon: 'lucideTrendingUp' },
];
